version: '3'

# DEFINE VARIABLES

services:
  gazebo-betaflight:
    container_name: gazebo_betaflight
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket:rw
      - ./betaflight_sim/models/iris_with_standoffs/model.sdf:/home/vehicle_gateway/src/vehicle_gateway/betaflight_sim/models/iris_with_standoffs/model.sdf:ro
      - ./betaflight_sim/worlds/empty_betaflight_world.sdf:/home/vehicle_gateway/src/vehicle_gateway/betaflight_sim/worlds/empty_betaflight_world.sdf:ro

  # This is a special container running ROS 1 + ROS 2 simultaneously. It is used to bridge the two frameworks.
  ros1-bridge:
      build:
        context: ./Docker/duckietown
        dockerfile: Dockerfile.ros2-ros1-bridge
      environment:
          - ROS_MASTER_URI=${ROS_MASTER_URI}
          - ROS_IP=${ROS_IP}
          - FASTRTPS_DEFAULT_PROFILES_FILE=/data/config/fastdds_no_shared_memory.xml
      volumes:
        - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
      network_mode: host
      command: ["bash", "-c", "source /ros_entrypoint.sh && rosparam load /data/config/bridge.yml && ros2 run ros1_bridge parameter_bridge"] 

  gazebo-ros2-bridge:
      build:
        context: ./Docker/duckietown
        dockerfile: Dockerfile.gz-garden-bridge
      environment:
          - FASTRTPS_DEFAULT_PROFILES_FILE=/data/config/fastdds_no_shared_memory.xml

      network_mode: host
      command: ["bash", "-c", "source /opt/ros/humble/setup.bash && source /ws/install/setup.bash && ros2 run ros_gz_bridge parameter_bridge --ros-args -p config_file:=/data/config/gazebo-bridge-config.yaml"]